sudo: required
services:
  - docker


before_install:
  - chmod +x /app
  - docker build -t akspawar/docker-react -f Dockerfile.dev .

script:
  - docker run akspawar/docker-react npm run test -- --coverage